[versions]
# libraries
annotations = "24.1.0"

# plugins
kotlin = "1.9.22"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.1"
qodana = "0.1.13"
rdgen = "2023.3.2"
# https://search.maven.org/artifact/com.jetbrains.rd/rd-gen

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
rdgen = { id = "com.jetbrains.rdgen", version.ref = "rdgen" }
