[versions]
# libraries
# https://search.maven.org/artifact/com.jetbrains.rd/rd-gen
rdGen = "2026.1.2"
opentest4j = "1.3.0"
serialization = "1.10.0"
junit = "4.13.2"
testng = "7.12.0"
grpc = "1.57.2"
grpcKotlin = "1.4.0"
protobuf = "3.24.4"

# plugins
kotlin = "2.3.10"
intelliJPlatform = "2.11.0"
changelog = "2.5.0"
protobufPlugin = "0.9.4"

[libraries]
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version.ref = "grpc" }
grpc-kotlin-stub = { group = "io.grpc", name = "grpc-kotlin-stub", version.ref = "grpcKotlin" }
grpc-netty-shaded = { group = "io.grpc", name = "grpc-netty-shaded", version.ref = "grpc" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobuf" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
